### ISSUE TITLE
Codecademy Hidden Courses

### ISSUE THREAD

**Issue by StevenCopeland** [hiddencodecademy/hiddencodecademy.github.io#1]
Add some CodeCademy hidden Courses to the list!

**Comment by vchrombie** [comment]
@StevenCopeland 
I have got some hidden courses.
Can I add them ?

**Comment by vchrombie** [comment]
@StevenCopeland 
I have submitted a pull request for a new link to Python course.

Can you please check that?

**Comment by vchrombie** [comment]
I want to add some style to this page so that it looks more attractive

**Comment by StevenCopeland** [comment]
@vchrombie change, add anything!

**Comment by ravinduramesh** [comment]
Looks like a fresh project. I also like to work on this.

**Comment by StevenCopeland** [comment]
@ravinduramesh Let's do this!

**Comment by SoldierCorp** [comment]
**UPDATE**:

Now we are using a json file to manage all the list of courses, please add your course to that file located in `data/courses.json`.

Thank you :)
