### ISSUE TITLE
Long list of courses

### ISSUE THREAD

**Issue by StevenCopeland** [hiddencodecademy/hiddencodecademy.github.io#13]
Here are some resources to get courses from:

https://www.codecademy.com/StevenCopeland/codebits/51Yd0m

https://discuss.codecademy.com/t/codecademy-hidden-courses/53032

https://github.com/A-J-C/CodecademyGroups/blob/master/Python%20For%20Beginners%20-%20Dustin%20Goodman/A%20List%20of%20Great%20Beta%20Python%20Courses%20-%20Glenn%20Richard.md

https://discuss.codecademy.com/t/community-project-gathering-non-track-courses/53249

https://discuss.codecademy.com/t/bonus-codecademy-courses/53080

**Comment by HimanshuAwasthi95** [comment]
can I participate on this issue

**Comment by StevenCopeland** [comment]
@HimanshuAwasthi95 Go for it!
