### ISSUE TITLE
Write a small guide on how to add a course.

### ISSUE THREAD

**Issue by nicolaihoilund** [hiddencodecademy/hiddencodecademy.github.io#30]
We need a small guide in the readme file to tell new visitors, how to add a course. It should be a bit more elegant than my simple explanation below.

How to:
Put it in the JSON file (data/courses.json) where it belongs. (url key with url string, name key with the title of the course (try to keep title short)).
Make sure to add a comma after the previous object.
If in doubt, check how the syntax for the other courses is.

**Comment by SoldierCorp** [comment]
I'll take this.
